apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: {{ .Values.app.name }}-pipeline-run-init
  namespace: {{ .Values.app.namespace }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    tekton.dev/pipeline: {{ .Values.git.repo }}-pipeline
    type: pipeline
spec:
  params:
    - name: source-repo
      value: {{ .Values.git.repo }}
    - name: source-branch
      value: main
    - name: output-image
      value: {{ include "image.url" . }}
  pipelineRef:
    name: {{ .Values.app.name }}-pipeline
  serviceAccountName: pipeline
  workspaces:
    - name: source-folder
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
