applicationName: ${{values.component_id}}-frontend
namespace: ${{values.namespace}}
targetEnvironment: dev
version: "1.0.0"
port: 8080
targetPort: 8080
routes: []
deploymentStrategy:
  type: RollingUpdate
  rollingMaxSurge: 25%
  rollingMaxUnavailable: 20%
replicaCount: 1
health:
  livenessEndpoint: /health
  readinessEndpoint: /health
  probeDelay: 5
  probePeriod: 10
  probeTimeout: 2
imageURL: "quay.io/openshiftlabs/app-mod-ordersfrontend:1.0"
env: []
image:
  repository: ${{values.image_host}}/${{values.image_name}}
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ${{values.image_tag}}