---
apiVersion: v1
kind: Secret
metadata:
  name: ${{ values.artifactId}}-repo
  namespace: devhub2
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ${{ values.destination }}