apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/categories: Build Tools
    tekton.dev/pipelines.minVersion: 0.17.0
    tekton.dev/platforms: 'linux/amd64,linux/s390x,linux/ppc64le'
    tekton.dev/tags: build-tool
  name: npm
  labels:
    app.kubernetes.io/version: '0.1'
spec:
  description: >-
    This task can be used to run npm goals on a project.

    This task can be used to run npm goals on a project where package.json is
    present and has some pre-defined npm scripts.
  params:
    - default: .
      description: The path where package.json of the project is defined.
      name: PATH_CONTEXT
      type: string
    - default:
        - version
      description: The npm goals you want to run.
      name: ARGS
      type: array
    - default: >-
        docker.io/library/node:12-alpine@sha256:dfbebf17bfb014e1e7068e76325a117bccf8679c68aec6a28514184a209c8bae
      description: The node image you want to use.
      name: IMAGE
      type: string
  steps:
    - args:
        - $(params.ARGS)
      command:
        - npm
      env:
        - name: CI
          value: 'true'
      image: $(params.IMAGE)
      name: npm-run
      resources: {}
      workingDir: $(workspaces.source.path)/$(params.PATH_CONTEXT)
  workspaces:
    - name: source
