---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ${{values.component_id}}
  namespace: ${{values.namespace}}
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  project: ${{values.component_id}}
  destinations:
    - name: local
      namespace: ${{values.namespace}}
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - url: ${{values.destination}}
  
